/gun/particle proton
/gun/energy 3 GeV
/gun/position 0 0 -600 cm
/gun/direction 0 0 1

#/random/setSeeds 34325 38473

/control/verbose 0
/tracking/verbose 0
/run/verbose 0
/event/verbose 0
/particle/verbose 0
/particle/property/verbose 0
/Prt/phys/verbose 0

#/process/eLoss/verbose 0
#/process/em/verbose 0
#/process/setVerbose 0
#/process/em/workerVerbose 0

#/Prt/geom/prtRotation 90 deg
/Prt/geom/lensId 0
/Prt/gun/optPhotonPolar

#/run/beamOn 1