#!/bin/bash

threads=4

rm b_iah*.root 
rm b_ial*.log

tseed=$(($(date +%s%N)/1000000-1393400000000))

echo $tseed

waitForMe (){
    while : 
    do
	activth=$(ps aux | grep "root.exe.*[p]rocData\|[p]rtdirc -[^m,^c]" | wc -l)
	printf "\r$statusline [$activth] ---- [$(($(date +%s) - start_time)) s] "
	sleep .1
	if [ "$activth" -lt "$1" ]; then 
	    break  
	fi
	sleep 1
    done
}


for theta in `LANG=en_us seq 20 5 140`; do
    for phi in `LANG=en_us seq -50 5 50`; do
	((tseed++))
	../build/prtdirc -o b_iah_${theta}_${phi}.root \
			 -h 1 -l 3 -p 7.00 -a $theta -phi $phi -gz 442.00 -gx 85.00 -gsx 66.10 -gsy 16.80 -z 10.00 -g 2018 -c 2018 -study 403 \
    			 -z 10 -e 1000 -x "mix" -b 1 -r $tseed > b_ial${tseed}.log &

	waitForMe $threads
    done
done   

sleep 2

hadd -f iahits.root b_iah*.root
