#!/bin/bash

rm b_h*.root 
rm b_l*.log

threads=22
tseed=$(($(date +%s%N)/1000000-1393400000000))

start_time=$(date +%s)
waitForMe (){
    while : 
    do 
	activth=$(ps aux | grep "[p]rtdirc|convert_int" | grep "dirc" | wc -l)
	printf "\r$statusline [$activth] ---- [$(($(date +%s) - start_time)) s] "
	if [ "$activth" -lt "$1" ]; then 
	    break  
	fi
	sleep 1
    done
}


if [ "$1" == "0" ] ; then 
    for i in {1..5}; do ../build/prtdirc -o b_h$i.root \
					 -h 1 -l 3 -p 7.00 -a 20.00 -phi 0.00 -gz 442.00 -gx 85.00 -gsx 66.10 -gsy 16.80 -z 10.00 -g 2018 -c 2018 -study 403 \
					 -s 1 -z 0 -a 180 -phi 0 -x "opticalphoton" -p "3.18 eV" -e 2000000 -b 1 \
					 -seed $tseed$i > b_l$i.log & done
    
else
    # for i in {1..5}; do ../build/prtdirc -o b_h$i.root \
    # 					 -h 1 -l 3 -p 7.00 -a 19.7 -phi 0.80 -gz 442.00 -gx 85.00 -gsx 66.10 -gsy 16.80 -z 10.00 -g 2018 -c 2018 -study 403 \
    # 					 -z 10 -e 1000 -x "mix" -b 1 -seed $tseed$i > b_l$i.log & done

    # for i in {1..20}; do ../build/prtdirc -o b_h$i.root \
    # 					  -h 1 -l 3 -p 7.00 -a 19.66 -phi -0.05 -gz 409.00 -gx 85.00 -gsx 65.00 -gsy 16.30 -z 10.00 -g 2018 -c 2018 -study 401 \
    # 			                  -e 10000 -x "mix_pip" -b 1 -seed $tseed$i > b_l$i.log & done

    for a in `LANG=en_us seq 20 0.5 140`; do
	# ../build/prtdirc -o hdata/b_h$a.root \
	# 		 -study 403 -r 0 -l 3 -w 0 -a $a \
    	# 		 -e 10000 -x "mix_pip" -b 1 -seed $tseed$a > hdata/b_l$a.log &
	
	# root -b -q draw_pat.C"(\"hdata/b_h$a.root\")"
	python convert_ind.py hdata/b_h$a.root &
	
	waitForMe $threads
    done 
fi

waitForMe 1
sleep 1

# if [ "$1" == "0" ] ; then 
#     hadd -f lut.root b_h*.root
# else
#     hadd -f hits_mix.root b_h*.root
# fi
