#!/bin/bash

threads=30
path="/d/proc/jun15/151"
#path="/data.local/data/jun15/"

waitForMe (){
    while : 
    do 
	activth=$(ps aux | grep "[p]rtdirc" | grep "r_b" | wc -l)
	printf "\r$statusline [$activth] ---- [$(($(date +%s) - start_time)) s] "
	sleep .1
	if [ "$activth" -lt "$1" ]; then 
	    break  
	fi
    done
}

start_time=$(date +%s)
statusline="Reco"
for i in `seq -0.015 0.0005 0.015` ; do
    for j in `seq -0.015 0.0005 0.015` ; do
	../build/prtdirc -s 2 -u ${path}/lut_beam_15177135523S10M_cs_avr.root -i ${path}/beam_15177135523C.root -o r_b_${i}_${j}.root -t1 1.5 -f -1 -e 1000 -v 0 -t2 ${i} -t3 ${j} -b 1  > /dev/null 2> /dev/null &
	waitForMe $threads
    done
done
waitForMe "1"
printf "\r$statusline [-] done [$(($(date +%s) - start_time)) s]         \n"


sleep 2
hadd -f r_sscan.root r_b_*.root
rm r_b_*.root 
