#!/bin/bash

threads=30
path="/d/proc/jun15/151"
#path="/data.local/data/jun15/"

waitForMe (){
    while : 
    do 
	activth=$(ps aux | grep "[p]rtdirc" | grep "b_" | wc -l)
	printf "\r$statusline [$activth] ---- [$(($(date +%s) - start_time)) s] "
	sleep .1
	if [ "$activth" -lt "$1" ]; then 
	    break  
	fi
    done
}

start_time=$(date +%s)

if [ ${1} == "1" ]; then
    statusline="Y step scan "
    for i in `seq 10 0.5 25` ; do
	../build/prtdirc -o b_l$i.root \
			 -p 7 -h 1 -l 3 -a 125 -gz 378 -gx 85 -gsx 67.5 -gsy ${i} -z 10  -g 2015 -c 2015 \
			 -s 1 -z 0 -a 180 -x "opticalphoton" -p "3.18 eV" -g 0 -e 5000000 -b 1 \
			 > l_b$i.log && \
	    root -q -b loadlib.C lutmean_cs.C"(\"b_l$i.root\")" && \
	    ../build/prtdirc -s 2 -u b_l$i.root -i ${path}/beam_15177135523C.root -o b_r_${i}.root -t1 1.5 -f -1 -e 2000 -v 0 -b 1 -t3 $i > /dev/null 2> /dev/null &
    done
    waitForMe "1"

    hadd -f r_step_scan.root b_r_*.root
    printf "\r$statusline [-] done [$(($(date +%s) - start_time)) s]         \n"
fi

if [ ${1} == "2" ]; then
    statusline="Divergence scan "
    for i in `seq -0.015 0.0005 0.015` ; do
	for j in `seq -0.015 0.0005 0.015` ; do
	    ../build/prtdirc -s 2 -u ${path}/lut_beam_15177135523S10M_cs_avr.root -i ${path}/beam_15177135523C.root -o b_r_${i}_${j}.root -t1 1.5 -f -1 -e 1000 -v 0 -t2 ${i} -t3 ${j} -b 1  > /dev/null 2> /dev/null &
	    waitForMe $threads
	done
    done
    waitForMe "1"
    printf "\r$statusline [-] done [$(($(date +%s) - start_time)) s]         \n"
    sleep 2
    hadd -f r_sscan.root b_r_*.root
fi

rm b_*.root 

